# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btype', models.IntegerField(choices=[(0, '-----'), (1, 'title'), (2, 'push'), (3, 'author')], default=0, verbose_name='type')),
                ('phrases', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name': 'BLACK LIST',
                'verbose_name_plural': 'BLACK LIST',
            },
        ),
        migrations.CreateModel(
            name='Joblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(default='running', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('entry', models.CharField(max_length=1024)),
                ('start', models.IntegerField(default=-1)),
                ('end', models.IntegerField(default=-1)),
                ('newest', models.IntegerField(default=-1)),
                ('status', models.CharField(default='debug', max_length=256)),
                ('blacklist', models.ManyToManyField(blank=True, to='crawl_app.Blacklist')),
            ],
            options={
                'verbose_name': 'SPIDER',
                'verbose_name_plural': 'SPIDER',
            },
        ),
    ]
