# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblog',
            options={'verbose_name': 'JOB LOG', 'verbose_name_plural': 'JOB LOG'},
        ),
        migrations.AlterField(
            model_name='joblog',
            name='finish_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
